use std::{env, fs, path::Path};

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let define_path = Path::new(&manifest).join("../define.h");
    let src = fs::read_to_string(&define_path).expect("Failed to read define.h");

    let mut out = String::new();
    out.push_str("// do not edit, for this was generated by build.rs\n");
    for line in src.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("#define ") {
            let mut parts = rest.split_whitespace();
            if let (Some(name), Some(val)) = (parts.next(), parts.next()) {
                let ty = if let Some(stripped) = val.strip_prefix("0x") {
                    if let Ok(num) = u32::from_str_radix(stripped, 16) {
                        if num <= 0xff { "u8" } else { "u32" }
                    } else {
                        "u32"
                    }
                } else if let Ok(num) = val.parse::<u32>() {
                    if num <= 0xff { "u8" } else { "u32" }
                } else {
                    "u32"
                };

                out.push_str(&format!(
                    "#[allow(dead_code)]\npub const {}: {} = {};//\n",
                    name, ty, val
                ));
            }
        }
    }
    let out_dir = env::var("OUT_DIR").unwrap();
    let dst = Path::new(&out_dir).join("opcodes.rs");
    fs::write(dst, out).expect("Failed to write opcodes.rs");
}
