use std::{env, fs, path::Path};

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let define_path = Path::new(&manifest).join("../define.h");
    let src = fs::read_to_string(&define_path).expect("Failed to read define.h");

    let mut out = String::new();
    out.push_str("// do not edit, for this was generated by build.rs\n");
    for line in src.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("#define ") {
            let mut parts = rest.split_whitespace();
            if let (Some(name), Some(val)) = (parts.next(), parts.next()) {
                out.push_str(&format!("pub const {}: u32 = {};//\n", name, val));
            }
        }
    }

    let out_dir = env::var("OUT_DIR").unwrap();
    let dst = Path::new(&out_dir).join("opcodes.rs");
    fs::write(dst, out).expect("Failed to write opcodes.rs");
}
