#ifndef OPCODES_H
#define OPCODES_H

#define STACK_SIZE 16384
#define REGISTERS 9

#define OPCODE_WRITE 0x01
#define OPCODE_NEWLINE 0x02
#define OPCODE_PRINT 0x03
#define OPCODE_PUSH_IMM 0x04
#define OPCODE_POP 0x05
#define OPCODE_ADD 0x06
#define OPCODE_SUB 0x07
#define OPCODE_MUL 0x08
#define OPCODE_DIV 0x09
#define OPCODE_PRINTREG 0x0A
#define OPCODE_MOV_IMM 0x0B
#define OPCODE_MOV_REG 0x0C
#define OPCODE_JMP 0x0D
#define OPCODE_JZ  0x0E
#define OPCODE_JNZ 0x0F
#define OPCODE_INC 0x10
#define OPCODE_DEC 0x11
#define OPCODE_PUSH_REG 0x12
#define OPCODE_CMP 0x13
#define OPCODE_HALT  0xFF

#endif