name: Make build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.sha }}
        name: Continuous build ${{ github.sha }}
        body: Build for commit ${{ github.sha }}
        files: |
          bbx
          bbxd
          bbxc
